#!/bin/bash

while [[ $# -gt 0 ]]; do
    case $1 in
        --part-uuid) PARTUUID_OPT=$2; shift 2;;
        --target) TARGET_OPT=$2; shift 2;;
        --output) OUTPUT_OPT=$2; shift 2;;
        --output-hello) OUTPUT_HELLO_OPT=$2; shift 2;;
        *) echo "Unrecognised param $1"; shift 1;;
    esac
done

if [[ -z $PARTUUID_OPT ]]; then
    echo "No --part-uuid option provided"
    OPTS_FAILED=1
fi

if [[ -z $TARGET_OPT ]]; then
    echo "No --target option provided"
    OPTS_FAILED=1
fi

[[ -n $OPTS_FAILED ]] && exit 1


ROOTDIR=$(realpath $(dirname $0))

make_efi() {
    make --always-make --file="$ROOTDIR/gnu-efi/apps/Makefile" "$1" clean VPATH="$ROOTDIR/gnu-efi/apps" TOPDIR="$ROOTDIR/gnu-efi" "$2"
}

make_efi forward.efi CFLAGS='-D PART_UUID=u\"'"${PARTUUID_OPT@U}"'\" -D TARGET=u\"'"$TARGET_OPT"'\"'
if [[ -n $OUTPUT_OPT ]]; then
    mv forward.efi $OUTPUT_OPT
fi

if [[ -n $OUTPUT_HELLO_OPT ]]; then
    make_efi hello.efi
    mv hello.efi $OUTPUT_HELLO_OPT
fi

sync
